In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(10)
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
l1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l2 = range(10)
print(l1, l2)
print(l1 == l2)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
True


In [6]:
# xrange: not generated immediately
for i in xrange(5):
    print(i)
    if i == 2: break

0
1
2


In [7]:
range(1, 5, 2) #2: step, starts from 1, < 5

[1, 3]