In [1]:
import numpy as np
import numpy.random as np_random

In [2]:
# 求平方根
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [3]:
# 数组比较
x = np_random.randn(8)
y = np_random.randn(8)
print(x)
print(y)
np.maximum(x, y)

[-1.73513146 -0.93189137  1.10662483 -0.20036815  0.14018401  0.70469504
  0.56580029 -0.13044112]
[ 0.40152097  1.03293838 -0.36604115 -1.15840552 -1.23235866 -0.05153246
 -1.37450028 -1.14564813]


array([ 0.40152097,  1.03293838,  1.10662483, -0.20036815,  0.14018401,
        0.70469504,  0.56580029, -0.13044112])

In [4]:
# 使用modf函数把浮点数分解成整数和小数部分
arr = np_random.randn(7) * 5  # 统一乘5
print(arr)
np.modf(arr)

[-2.06575024 -0.92319273 -1.37649306 -0.11705042  6.20745895  0.14962426
  2.46829254]


(array([-0.06575024, -0.92319273, -0.37649306, -0.11705042,  0.20745895,
         0.14962426,  0.46829254]), array([-2., -0., -1., -0.,  6.,  0.,  2.]))