# numpy 创建 ndarray

In [1]:
import numpy as np

print('使用普通一维数组生成NumPy一维数组')
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
print(arr)
print('打印元素类型')
print(arr.dtype)

使用普通一维数组生成NumPy一维数组
[ 6.   7.5  8.   0.   1. ]
打印元素类型
float64


In [2]:
print('使用普通二维数组生成NumPy二维数组')
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)
print(arr)
print('打印数组维度')
print(arr.shape)

使用普通二维数组生成NumPy二维数组
[[1 2 3 4]
 [5 6 7 8]]
打印数组维度
(2L, 4L)


In [3]:
print('使用zeros/empty')
print(np.zeros(10)) # 生成包含10个0的一维数组
print(np.zeros((3, 6))) # 生成3*6的二维数组
print(np.empty((2, 3, 2))) # 生成2*3*2的三维数组，所有元素未初始化。

使用zeros/empty
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  1.22034215e-321   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]

 [[  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]]


In [4]:
print('使用arrange生成连续元素')
print(np.arange(15)) # [0, 1, 2, ..., 14]

使用arrange生成连续元素
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# numpy 数据类型

In [5]:
import numpy as np

print('生成数组时指定数据类型')
arr = np.array([1, 2, 3], dtype = np.float64)
print(arr.dtype)
arr = np.array([1, 2, 3], dtype = np.int32)
print(arr.dtype)

生成数组时指定数据类型
float64
int32


In [6]:
print('使用astype复制数组并转换数据类型')
int_arr = np.array([1, 2, 3, 4, 5])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

使用astype复制数组并转换数据类型
int32
float64


In [7]:
print('使用astype将float转换为int时小数部分被舍弃')
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype = np.int)
print(int_arr)

使用astype将float转换为int时小数部分被舍弃
[ 3 -1 -2  0 12 10]


In [8]:
print('使用astype把字符串转换为数组，如果失败抛出异常。')
str_arr = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
float_arr = str_arr.astype(dtype = np.float)
print(float_arr)

使用astype把字符串转换为数组，如果失败抛出异常。
[  1.25  -9.6   42.  ]


In [9]:
print('astype使用其它数组的数据类型作为参数')
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype = np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr[0], int_arr[1])  # astype做了复制，数组本身不变。

astype使用其它数组的数据类型作为参数
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
(0, 1)


# Operations between arrays and scalars

In [10]:
import numpy as np

# 数组乘法／减法，对应元素相乘／相减。
arr = np.array([[1.0, 2.0, 3.0], [4., 5., 6.]])
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [11]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
# 标量操作作用在数组的每个元素上
arr = np.array([[1.0, 2.0, 3.0], [4., 5., 6.]])
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [13]:
arr ** 0.5  # 开根号

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])